name: Publish

on:
    workflow_dispatch:
        inputs:
            pack_version:
                description: 'Datapack version code'
                required: true
                type: string
            mc_version:
                description: 'Required Minecraft version'
                required: true
                type: string
            version_type:
                required: true
                type: choice
                options:
                    - release
                    - beta
                    - alpha

jobs:
    test:
        name: Lint Test
        uses: ./.github/workflows/test.yml
    publish:
        name: Publish
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Install Dependences
              run: |
                sudo apt install zip
            - name: Prepare Deployment File
              run: |
                zip ./mcfdpatch.zip -r ./data/ ./pack.mcmeta
            - uses: Kir-Antipov/mc-publish@v3.3
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}

                modrinth-id: qzywxGQ9
                modrinth-token: ${{ secrets.MODRINTH_PUBLISH_TOKEN }}

                version: ${{ inputs.mc_version }}-${{ inputs.pack_version }}${{ inputs.version_type }}
                files: |
                  ./mcfdpatch.zip
                dependencies: ${{ vars.MODRINTH_DEPEND}}
                loaders: datapack