name: Lint-Test
on:
    #push:
    #    branches:
    #        - main
    pull_request:
    workflow_call:

jobs:
    lint:
        name: Lint Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/setup-node@v4
            - name: install linters
              run: |
                npm install xo --save-dev
            - name: Linting
              uses: wearerequired/lint-action@v2
              with:
                xo: true